// B-100 — Canonical ISO 3166-1 alpha-3 country list (249 entries).
//
// Used by the shared `<CountrySelect>` so passport/nationality/jurisdiction
// values store an ISO3 code while displaying the country name. The AI
// passport extractor (`src/lib/ai/verifyDocument.ts`) also returns ISO3
// — the post-processor falls back to `NAME_TO_ISO3` if the model emits
// a name instead of a code.
//
// `numeric` is unused today but retained as free metadata for any
// future regulatory export. Source: ISO 3166-1:2020.

export interface Country {
  iso3: string;
  name: string;
  numeric: string;
}

export const COUNTRIES_ISO: Country[] = [
  { iso3: "AFG", name: "Afghanistan", numeric: "004" },
  { iso3: "ALB", name: "Albania", numeric: "008" },
  { iso3: "DZA", name: "Algeria", numeric: "012" },
  { iso3: "ASM", name: "American Samoa", numeric: "016" },
  { iso3: "AND", name: "Andorra", numeric: "020" },
  { iso3: "AGO", name: "Angola", numeric: "024" },
  { iso3: "AIA", name: "Anguilla", numeric: "660" },
  { iso3: "ATA", name: "Antarctica", numeric: "010" },
  { iso3: "ATG", name: "Antigua and Barbuda", numeric: "028" },
  { iso3: "ARG", name: "Argentina", numeric: "032" },
  { iso3: "ARM", name: "Armenia", numeric: "051" },
  { iso3: "ABW", name: "Aruba", numeric: "533" },
  { iso3: "AUS", name: "Australia", numeric: "036" },
  { iso3: "AUT", name: "Austria", numeric: "040" },
  { iso3: "AZE", name: "Azerbaijan", numeric: "031" },
  { iso3: "BHS", name: "Bahamas", numeric: "044" },
  { iso3: "BHR", name: "Bahrain", numeric: "048" },
  { iso3: "BGD", name: "Bangladesh", numeric: "050" },
  { iso3: "BRB", name: "Barbados", numeric: "052" },
  { iso3: "BLR", name: "Belarus", numeric: "112" },
  { iso3: "BEL", name: "Belgium", numeric: "056" },
  { iso3: "BLZ", name: "Belize", numeric: "084" },
  { iso3: "BEN", name: "Benin", numeric: "204" },
  { iso3: "BMU", name: "Bermuda", numeric: "060" },
  { iso3: "BTN", name: "Bhutan", numeric: "064" },
  { iso3: "BOL", name: "Bolivia", numeric: "068" },
  { iso3: "BES", name: "Bonaire, Sint Eustatius and Saba", numeric: "535" },
  { iso3: "BIH", name: "Bosnia and Herzegovina", numeric: "070" },
  { iso3: "BWA", name: "Botswana", numeric: "072" },
  { iso3: "BVT", name: "Bouvet Island", numeric: "074" },
  { iso3: "BRA", name: "Brazil", numeric: "076" },
  { iso3: "IOT", name: "British Indian Ocean Territory", numeric: "086" },
  { iso3: "BRN", name: "Brunei Darussalam", numeric: "096" },
  { iso3: "BGR", name: "Bulgaria", numeric: "100" },
  { iso3: "BFA", name: "Burkina Faso", numeric: "854" },
  { iso3: "BDI", name: "Burundi", numeric: "108" },
  { iso3: "CPV", name: "Cabo Verde", numeric: "132" },
  { iso3: "KHM", name: "Cambodia", numeric: "116" },
  { iso3: "CMR", name: "Cameroon", numeric: "120" },
  { iso3: "CAN", name: "Canada", numeric: "124" },
  { iso3: "CYM", name: "Cayman Islands", numeric: "136" },
  { iso3: "CAF", name: "Central African Republic", numeric: "140" },
  { iso3: "TCD", name: "Chad", numeric: "148" },
  { iso3: "CHL", name: "Chile", numeric: "152" },
  { iso3: "CHN", name: "China", numeric: "156" },
  { iso3: "CXR", name: "Christmas Island", numeric: "162" },
  { iso3: "CCK", name: "Cocos (Keeling) Islands", numeric: "166" },
  { iso3: "COL", name: "Colombia", numeric: "170" },
  { iso3: "COM", name: "Comoros", numeric: "174" },
  { iso3: "COD", name: "Congo (Democratic Republic of the)", numeric: "180" },
  { iso3: "COG", name: "Congo (Republic of the)", numeric: "178" },
  { iso3: "COK", name: "Cook Islands", numeric: "184" },
  { iso3: "CRI", name: "Costa Rica", numeric: "188" },
  { iso3: "CIV", name: "Côte d'Ivoire", numeric: "384" },
  { iso3: "HRV", name: "Croatia", numeric: "191" },
  { iso3: "CUB", name: "Cuba", numeric: "192" },
  { iso3: "CUW", name: "Curaçao", numeric: "531" },
  { iso3: "CYP", name: "Cyprus", numeric: "196" },
  { iso3: "CZE", name: "Czechia", numeric: "203" },
  { iso3: "DNK", name: "Denmark", numeric: "208" },
  { iso3: "DJI", name: "Djibouti", numeric: "262" },
  { iso3: "DMA", name: "Dominica", numeric: "212" },
  { iso3: "DOM", name: "Dominican Republic", numeric: "214" },
  { iso3: "ECU", name: "Ecuador", numeric: "218" },
  { iso3: "EGY", name: "Egypt", numeric: "818" },
  { iso3: "SLV", name: "El Salvador", numeric: "222" },
  { iso3: "GNQ", name: "Equatorial Guinea", numeric: "226" },
  { iso3: "ERI", name: "Eritrea", numeric: "232" },
  { iso3: "EST", name: "Estonia", numeric: "233" },
  { iso3: "SWZ", name: "Eswatini", numeric: "748" },
  { iso3: "ETH", name: "Ethiopia", numeric: "231" },
  { iso3: "FLK", name: "Falkland Islands", numeric: "238" },
  { iso3: "FRO", name: "Faroe Islands", numeric: "234" },
  { iso3: "FJI", name: "Fiji", numeric: "242" },
  { iso3: "FIN", name: "Finland", numeric: "246" },
  { iso3: "FRA", name: "France", numeric: "250" },
  { iso3: "GUF", name: "French Guiana", numeric: "254" },
  { iso3: "PYF", name: "French Polynesia", numeric: "258" },
  { iso3: "ATF", name: "French Southern Territories", numeric: "260" },
  { iso3: "GAB", name: "Gabon", numeric: "266" },
  { iso3: "GMB", name: "Gambia", numeric: "270" },
  { iso3: "GEO", name: "Georgia", numeric: "268" },
  { iso3: "DEU", name: "Germany", numeric: "276" },
  { iso3: "GHA", name: "Ghana", numeric: "288" },
  { iso3: "GIB", name: "Gibraltar", numeric: "292" },
  { iso3: "GRC", name: "Greece", numeric: "300" },
  { iso3: "GRL", name: "Greenland", numeric: "304" },
  { iso3: "GRD", name: "Grenada", numeric: "308" },
  { iso3: "GLP", name: "Guadeloupe", numeric: "312" },
  { iso3: "GUM", name: "Guam", numeric: "316" },
  { iso3: "GTM", name: "Guatemala", numeric: "320" },
  { iso3: "GGY", name: "Guernsey", numeric: "831" },
  { iso3: "GIN", name: "Guinea", numeric: "324" },
  { iso3: "GNB", name: "Guinea-Bissau", numeric: "624" },
  { iso3: "GUY", name: "Guyana", numeric: "328" },
  { iso3: "HTI", name: "Haiti", numeric: "332" },
  { iso3: "HMD", name: "Heard Island and McDonald Islands", numeric: "334" },
  { iso3: "VAT", name: "Holy See (Vatican City)", numeric: "336" },
  { iso3: "HND", name: "Honduras", numeric: "340" },
  { iso3: "HKG", name: "Hong Kong", numeric: "344" },
  { iso3: "HUN", name: "Hungary", numeric: "348" },
  { iso3: "ISL", name: "Iceland", numeric: "352" },
  { iso3: "IND", name: "India", numeric: "356" },
  { iso3: "IDN", name: "Indonesia", numeric: "360" },
  { iso3: "IRN", name: "Iran", numeric: "364" },
  { iso3: "IRQ", name: "Iraq", numeric: "368" },
  { iso3: "IRL", name: "Ireland", numeric: "372" },
  { iso3: "IMN", name: "Isle of Man", numeric: "833" },
  { iso3: "ISR", name: "Israel", numeric: "376" },
  { iso3: "ITA", name: "Italy", numeric: "380" },
  { iso3: "JAM", name: "Jamaica", numeric: "388" },
  { iso3: "JPN", name: "Japan", numeric: "392" },
  { iso3: "JEY", name: "Jersey", numeric: "832" },
  { iso3: "JOR", name: "Jordan", numeric: "400" },
  { iso3: "KAZ", name: "Kazakhstan", numeric: "398" },
  { iso3: "KEN", name: "Kenya", numeric: "404" },
  { iso3: "KIR", name: "Kiribati", numeric: "296" },
  { iso3: "PRK", name: "Korea (Democratic People's Republic of)", numeric: "408" },
  { iso3: "KOR", name: "Korea (Republic of)", numeric: "410" },
  { iso3: "KWT", name: "Kuwait", numeric: "414" },
  { iso3: "KGZ", name: "Kyrgyzstan", numeric: "417" },
  { iso3: "LAO", name: "Laos", numeric: "418" },
  { iso3: "LVA", name: "Latvia", numeric: "428" },
  { iso3: "LBN", name: "Lebanon", numeric: "422" },
  { iso3: "LSO", name: "Lesotho", numeric: "426" },
  { iso3: "LBR", name: "Liberia", numeric: "430" },
  { iso3: "LBY", name: "Libya", numeric: "434" },
  { iso3: "LIE", name: "Liechtenstein", numeric: "438" },
  { iso3: "LTU", name: "Lithuania", numeric: "440" },
  { iso3: "LUX", name: "Luxembourg", numeric: "442" },
  { iso3: "MAC", name: "Macao", numeric: "446" },
  { iso3: "MDG", name: "Madagascar", numeric: "450" },
  { iso3: "MWI", name: "Malawi", numeric: "454" },
  { iso3: "MYS", name: "Malaysia", numeric: "458" },
  { iso3: "MDV", name: "Maldives", numeric: "462" },
  { iso3: "MLI", name: "Mali", numeric: "466" },
  { iso3: "MLT", name: "Malta", numeric: "470" },
  { iso3: "MHL", name: "Marshall Islands", numeric: "584" },
  { iso3: "MTQ", name: "Martinique", numeric: "474" },
  { iso3: "MRT", name: "Mauritania", numeric: "478" },
  { iso3: "MUS", name: "Mauritius", numeric: "480" },
  { iso3: "MYT", name: "Mayotte", numeric: "175" },
  { iso3: "MEX", name: "Mexico", numeric: "484" },
  { iso3: "FSM", name: "Micronesia (Federated States of)", numeric: "583" },
  { iso3: "MDA", name: "Moldova", numeric: "498" },
  { iso3: "MCO", name: "Monaco", numeric: "492" },
  { iso3: "MNG", name: "Mongolia", numeric: "496" },
  { iso3: "MNE", name: "Montenegro", numeric: "499" },
  { iso3: "MSR", name: "Montserrat", numeric: "500" },
  { iso3: "MAR", name: "Morocco", numeric: "504" },
  { iso3: "MOZ", name: "Mozambique", numeric: "508" },
  { iso3: "MMR", name: "Myanmar", numeric: "104" },
  { iso3: "NAM", name: "Namibia", numeric: "516" },
  { iso3: "NRU", name: "Nauru", numeric: "520" },
  { iso3: "NPL", name: "Nepal", numeric: "524" },
  { iso3: "NLD", name: "Netherlands", numeric: "528" },
  { iso3: "NCL", name: "New Caledonia", numeric: "540" },
  { iso3: "NZL", name: "New Zealand", numeric: "554" },
  { iso3: "NIC", name: "Nicaragua", numeric: "558" },
  { iso3: "NER", name: "Niger", numeric: "562" },
  { iso3: "NGA", name: "Nigeria", numeric: "566" },
  { iso3: "NIU", name: "Niue", numeric: "570" },
  { iso3: "NFK", name: "Norfolk Island", numeric: "574" },
  { iso3: "MKD", name: "North Macedonia", numeric: "807" },
  { iso3: "MNP", name: "Northern Mariana Islands", numeric: "580" },
  { iso3: "NOR", name: "Norway", numeric: "578" },
  { iso3: "OMN", name: "Oman", numeric: "512" },
  { iso3: "PAK", name: "Pakistan", numeric: "586" },
  { iso3: "PLW", name: "Palau", numeric: "585" },
  { iso3: "PSE", name: "Palestine", numeric: "275" },
  { iso3: "PAN", name: "Panama", numeric: "591" },
  { iso3: "PNG", name: "Papua New Guinea", numeric: "598" },
  { iso3: "PRY", name: "Paraguay", numeric: "600" },
  { iso3: "PER", name: "Peru", numeric: "604" },
  { iso3: "PHL", name: "Philippines", numeric: "608" },
  { iso3: "PCN", name: "Pitcairn", numeric: "612" },
  { iso3: "POL", name: "Poland", numeric: "616" },
  { iso3: "PRT", name: "Portugal", numeric: "620" },
  { iso3: "PRI", name: "Puerto Rico", numeric: "630" },
  { iso3: "QAT", name: "Qatar", numeric: "634" },
  { iso3: "REU", name: "Réunion", numeric: "638" },
  { iso3: "ROU", name: "Romania", numeric: "642" },
  { iso3: "RUS", name: "Russia", numeric: "643" },
  { iso3: "RWA", name: "Rwanda", numeric: "646" },
  { iso3: "BLM", name: "Saint Barthélemy", numeric: "652" },
  { iso3: "SHN", name: "Saint Helena, Ascension and Tristan da Cunha", numeric: "654" },
  { iso3: "KNA", name: "Saint Kitts and Nevis", numeric: "659" },
  { iso3: "LCA", name: "Saint Lucia", numeric: "662" },
  { iso3: "MAF", name: "Saint Martin (French part)", numeric: "663" },
  { iso3: "SPM", name: "Saint Pierre and Miquelon", numeric: "666" },
  { iso3: "VCT", name: "Saint Vincent and the Grenadines", numeric: "670" },
  { iso3: "WSM", name: "Samoa", numeric: "882" },
  { iso3: "SMR", name: "San Marino", numeric: "674" },
  { iso3: "STP", name: "São Tomé and Príncipe", numeric: "678" },
  { iso3: "SAU", name: "Saudi Arabia", numeric: "682" },
  { iso3: "SEN", name: "Senegal", numeric: "686" },
  { iso3: "SRB", name: "Serbia", numeric: "688" },
  { iso3: "SYC", name: "Seychelles", numeric: "690" },
  { iso3: "SLE", name: "Sierra Leone", numeric: "694" },
  { iso3: "SGP", name: "Singapore", numeric: "702" },
  { iso3: "SXM", name: "Sint Maarten (Dutch part)", numeric: "534" },
  { iso3: "SVK", name: "Slovakia", numeric: "703" },
  { iso3: "SVN", name: "Slovenia", numeric: "705" },
  { iso3: "SLB", name: "Solomon Islands", numeric: "090" },
  { iso3: "SOM", name: "Somalia", numeric: "706" },
  { iso3: "ZAF", name: "South Africa", numeric: "710" },
  { iso3: "SGS", name: "South Georgia and the South Sandwich Islands", numeric: "239" },
  { iso3: "SSD", name: "South Sudan", numeric: "728" },
  { iso3: "ESP", name: "Spain", numeric: "724" },
  { iso3: "LKA", name: "Sri Lanka", numeric: "144" },
  { iso3: "SDN", name: "Sudan", numeric: "729" },
  { iso3: "SUR", name: "Suriname", numeric: "740" },
  { iso3: "SJM", name: "Svalbard and Jan Mayen", numeric: "744" },
  { iso3: "SWE", name: "Sweden", numeric: "752" },
  { iso3: "CHE", name: "Switzerland", numeric: "756" },
  { iso3: "SYR", name: "Syria", numeric: "760" },
  { iso3: "TWN", name: "Taiwan", numeric: "158" },
  { iso3: "TJK", name: "Tajikistan", numeric: "762" },
  { iso3: "TZA", name: "Tanzania", numeric: "834" },
  { iso3: "THA", name: "Thailand", numeric: "764" },
  { iso3: "TLS", name: "Timor-Leste", numeric: "626" },
  { iso3: "TGO", name: "Togo", numeric: "768" },
  { iso3: "TKL", name: "Tokelau", numeric: "772" },
  { iso3: "TON", name: "Tonga", numeric: "776" },
  { iso3: "TTO", name: "Trinidad and Tobago", numeric: "780" },
  { iso3: "TUN", name: "Tunisia", numeric: "788" },
  { iso3: "TUR", name: "Türkiye", numeric: "792" },
  { iso3: "TKM", name: "Turkmenistan", numeric: "795" },
  { iso3: "TCA", name: "Turks and Caicos Islands", numeric: "796" },
  { iso3: "TUV", name: "Tuvalu", numeric: "798" },
  { iso3: "UGA", name: "Uganda", numeric: "800" },
  { iso3: "UKR", name: "Ukraine", numeric: "804" },
  { iso3: "ARE", name: "United Arab Emirates", numeric: "784" },
  { iso3: "GBR", name: "United Kingdom", numeric: "826" },
  { iso3: "USA", name: "United States", numeric: "840" },
  { iso3: "UMI", name: "United States Minor Outlying Islands", numeric: "581" },
  { iso3: "URY", name: "Uruguay", numeric: "858" },
  { iso3: "UZB", name: "Uzbekistan", numeric: "860" },
  { iso3: "VUT", name: "Vanuatu", numeric: "548" },
  { iso3: "VEN", name: "Venezuela", numeric: "862" },
  { iso3: "VNM", name: "Vietnam", numeric: "704" },
  { iso3: "VGB", name: "Virgin Islands (British)", numeric: "092" },
  { iso3: "VIR", name: "Virgin Islands (U.S.)", numeric: "850" },
  { iso3: "WLF", name: "Wallis and Futuna", numeric: "876" },
  { iso3: "ESH", name: "Western Sahara", numeric: "732" },
  { iso3: "YEM", name: "Yemen", numeric: "887" },
  { iso3: "ZMB", name: "Zambia", numeric: "894" },
  { iso3: "ZWE", name: "Zimbabwe", numeric: "716" },
];

export const ISO3_TO_NAME: Record<string, string> = Object.fromEntries(
  COUNTRIES_ISO.map((c) => [c.iso3, c.name]),
);

// `lowercased name → ISO3` for legacy-name fallback when callers pass a
// free-form country name instead of a code (e.g. older DB rows, AI
// extractor pre-prompt-update, hand-entered values).
const NAME_ALIASES: Record<string, string> = {
  // Common short / unofficial names mapped to canonical ISO3.
  "united states of america": "USA",
  "us": "USA",
  "u.s.": "USA",
  "u.s.a.": "USA",
  "uk": "GBR",
  "u.k.": "GBR",
  "great britain": "GBR",
  "england": "GBR",
  "scotland": "GBR",
  "wales": "GBR",
  "northern ireland": "GBR",
  "south korea": "KOR",
  "north korea": "PRK",
  "russian federation": "RUS",
  "vatican city": "VAT",
  "ivory coast": "CIV",
  "burma": "MMR",
  "swaziland": "SWZ",
  "czech republic": "CZE",
  "macedonia": "MKD",
  "cape verde": "CPV",
  "east timor": "TLS",
  "citizen of mauritius": "MUS",
  "mauritian": "MUS",
};

export const NAME_TO_ISO3: Record<string, string> = {
  ...Object.fromEntries(COUNTRIES_ISO.map((c) => [c.name.toLowerCase(), c.iso3])),
  ...NAME_ALIASES,
};

export function isValidIso3(value: unknown): value is string {
  return typeof value === "string" && /^[A-Z]{3}$/.test(value) && value in ISO3_TO_NAME;
}

export function nameForIso3(value: string | null | undefined): string | null {
  if (!value) return null;
  return ISO3_TO_NAME[value] ?? null;
}

/**
 * Resolve a free-form country value (legacy name or ISO3) to an ISO3 code.
 * Returns `null` when no match.
 */
export function toIso3(value: string | null | undefined): string | null {
  if (!value) return null;
  const v = value.trim();
  if (!v) return null;
  if (isValidIso3(v.toUpperCase())) return v.toUpperCase();
  return NAME_TO_ISO3[v.toLowerCase()] ?? null;
}
