import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { getTenantId } from "@/lib/tenant";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY!);

export async function POST(
  request: Request,
  { params }: { params: { id: string } }
) {
  const session = await auth();
  if (!session || session.user.role !== "admin") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const supabase = createAdminClient();
  const tenantId = getTenantId(session);

  const body = await request.json() as {
    service_id: string;
    sent_to_profile_id: string;
    note: string;
    auto_populated_from_flags?: boolean;
  };

  if (!body.service_id || !body.sent_to_profile_id || !body.note?.trim()) {
    return NextResponse.json({ error: "service_id, sent_to_profile_id, and note are required" }, { status: 400 });
  }

  // Get document + document type name
  const { data: doc } = await supabase
    .from("documents")
    .select("id, file_name, service_id, document_type_id, document_types(name)")
    .eq("id", params.id)
    .maybeSingle();

  if (!doc) return NextResponse.json({ error: "Document not found" }, { status: 404 });

  const docTypeName = (doc.document_types as unknown as { name: string } | null)?.name ?? "Document";

  // Get service + template name
  const { data: svc } = await supabase
    .from("services")
    .select("service_templates(name)")
    .eq("id", body.service_id)
    .maybeSingle();
  const serviceName = (svc?.service_templates as unknown as { name: string } | null)?.name ?? "your service";

  // Get recipient profile
  const { data: profile } = await supabase
    .from("client_profiles")
    .select("id, full_name, email")
    .eq("id", body.sent_to_profile_id)
    .eq("tenant_id", tenantId)
    .maybeSingle();

  if (!profile?.email) {
    return NextResponse.json({ error: "Recipient has no email address" }, { status: 400 });
  }

  // Insert update request row
  const { data: requestRow, error: insertErr } = await supabase
    .from("document_update_requests")
    .insert({
      document_id: params.id,
      service_id: body.service_id,
      tenant_id: tenantId,
      requested_by: session.user.id,
      requested_by_name: session.user.name ?? null,
      sent_to_profile_id: body.sent_to_profile_id,
      sent_to_email: profile.email,
      note: body.note.trim(),
      auto_populated_from_flags: body.auto_populated_from_flags ?? false,
    })
    .select("id, sent_at")
    .single();

  if (insertErr || !requestRow) {
    return NextResponse.json({ error: insertErr?.message ?? "Insert failed" }, { status: 500 });
  }

  // Send email
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
  const senderName = session.user.name ?? "GWMS";

  const { error: emailError } = await resend.emails.send({
    from: `GWMS Client Portal <${process.env.RESEND_FROM_EMAIL!}>`,
    to: profile.email,
    subject: `Document Update Required — ${docTypeName} for ${serviceName}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: #1a365d; padding: 24px; text-align: center;">
          <h1 style="color: white; margin: 0; font-size: 22px;">GWMS Client Portal</h1>
          <p style="color: #90cdf4; margin: 6px 0 0; font-size: 13px;">KYC / AML Compliance Portal</p>
        </div>
        <div style="padding: 36px; background: #ffffff;">
          <p style="color: #1a365d; font-size: 16px; margin: 0 0 12px;">Dear ${profile.full_name ?? ""},</p>
          <p style="color: #4a5568; font-size: 14px; line-height: 1.6;">
            An update is required for your <strong>${docTypeName}</strong> submitted for the
            <strong>${serviceName}</strong> application at GWMS.
          </p>
          <p style="color: #4a5568; font-size: 14px; line-height: 1.6; margin-top: 16px;">
            <strong>Note from reviewer:</strong>
          </p>
          <div style="background: #f4f4f5; padding: 16px; border-radius: 8px; margin: 8px 0 24px; border-left: 3px solid #1a365d;">
            <p style="color: #4a5568; font-size: 14px; margin: 0; white-space: pre-wrap;">${body.note.trim()}</p>
          </div>
          <div style="text-align: center; margin: 32px 0;">
            <a href="${baseUrl}/dashboard"
               style="background: #1a365d; color: white; padding: 14px 32px; border-radius: 6px;
                      text-decoration: none; font-size: 15px; font-weight: 600; display: inline-block;">
              Log in to update →
            </a>
          </div>
          <p style="color: #a0aec0; font-size: 12px; margin-top: 24px;">
            This email was autogenerated on behalf of ${senderName}.
          </p>
        </div>
        <div style="padding: 20px; background: #f7fafc; text-align: center; font-size: 12px; color: #718096;">
          GWMS Client Portal | Mauritius
        </div>
      </div>
    `,
  });

  if (emailError) {
    // Row already inserted — don't fail; log the warning server-side only
    return NextResponse.json({
      ok: true,
      request_id: requestRow.id,
      sent_at: requestRow.sent_at,
      email_warning: emailError.message,
    });
  }

  return NextResponse.json({ ok: true, request_id: requestRow.id, sent_at: requestRow.sent_at });
}
