-- B-098 follow-up — repoint `admin_users.user_id` FK to public.users(id).
--
-- The previous migration (`20260513012213_admin_users_user_id_fkey.sql`)
-- was a no-op: a constraint named `admin_users_user_id_fkey` already
-- existed, auto-generated by the original CREATE TABLE which references
-- `profiles(id)`. Verified post-push by hitting the Supabase JS join
-- `from("admin_users").select("user_id, users(full_name, email)")` —
-- still PGRST200 "Could not find a relationship between 'admin_users'
-- and 'users' in the schema cache". All three admin_users rows already
-- have matching `public.users` rows by id, so a clean repoint is safe.
--
-- This migration drops every FK currently anchored on
-- `admin_users.user_id` regardless of target / name, then adds the
-- canonical one to `public.users(id)`. Idempotent: a re-run finds the
-- new FK already in place and exits.

DO $$
DECLARE
  cons record;
  target_oid oid := 'public.users'::regclass;
  already_correct boolean := false;
BEGIN
  FOR cons IN
    SELECT conname, confrelid
    FROM pg_constraint
    WHERE conrelid = 'public.admin_users'::regclass
      AND contype = 'f'
      AND conkey = ARRAY[
        (SELECT attnum FROM pg_attribute
          WHERE attrelid = 'public.admin_users'::regclass
            AND attname = 'user_id')
      ]
  LOOP
    IF cons.confrelid = target_oid
       AND cons.conname = 'admin_users_user_id_fkey' THEN
      already_correct := true;
    ELSE
      EXECUTE format(
        'ALTER TABLE public.admin_users DROP CONSTRAINT %I',
        cons.conname
      );
    END IF;
  END LOOP;

  IF NOT already_correct THEN
    ALTER TABLE public.admin_users
      ADD CONSTRAINT admin_users_user_id_fkey
      FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
  END IF;
END $$;

-- Force PostgREST to refresh its schema cache so the join resolves
-- immediately (Supabase listens for this notification).
NOTIFY pgrst, 'reload schema';
